version: '3'

services:
  php:
    volumes:
      - ~/.ssh:/root/.ssh:ro

  web:
    ports:
      - "8080:80"

  # db:
  #   ports:
  #     - "3307:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8888:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app_network

