version: '3.8'

services:
  php:
    build:
      context: docker/php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app_network

  web:
    build:
      context: docker/nginx
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app_network

  db:
    image: mariadb:10.3
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - app_network

volumes:
  database:

networks:
  app_network:
